'use client'

import { useState } from 'react'
import { useCompletion } from 'ai/react'

import { Separator } from '@/components/ui/separator'
import { Textarea } from '@/components/ui/textarea'
import { VideoInputForm } from './forms/video-input-form'
import { RunAIForm } from './forms/run-ai-form'

export function Content() {
  const [temperature, setTemperature] = useState(0.5)
  const [videoId, setVideoId] = useState('')

  const {
    input,
    setInput,
    handleInputChange,
    handleSubmit,
    completion,
    isLoading,
  } = useCompletion({
    api: 'http://localhost:3333/ai/complete',
    headers: { 'Content-Type': 'application/json' },
    body: {
      videoId,
      temperature,
    },
  })

  function handleTemperatureChange(value: number) {
    setTemperature(value)
  }

  function handleVideoUpload(id: string) {
    setVideoId(id)
  }

  return (
    <main className="flex-1 px-6 py-4 flex gap-6">
      <div className="flex flex-col flex-1 gap-4">
        <div className="grid grid-rows-2 gap-4 flex-1">
          <Textarea
            className="resize-none p-4 leading-relaxed"
            placeholder="Enter the prompt for the AI..."
            value={input}
            onChange={handleInputChange}
          />
          <Textarea
            className="resize-none p-4 leading-relaxed"
            placeholder="Results generated by AI..."
            value={completion}
            readOnly
          />
        </div>

        <p className="text-sm text-muted-foreground">
          Remember: you can use the{' '}
          <code className="text-violet-400">{'{transcription}'}</code> variable
          in your prompt to insert the transcripted content of your video
        </p>
      </div>

      <div className="w-80 space-y-6">
        <VideoInputForm onVideoUploaded={handleVideoUpload} />

        <Separator />

        <RunAIForm
          handleSubmit={handleSubmit}
          handlePromptSelected={setInput}
          handleTemperatureChange={handleTemperatureChange}
          temperature={temperature}
          isLoading={isLoading}
        />
      </div>
    </main>
  )
}
