'use client'

import { useState } from 'react'

import { Separator } from '@/components/ui/separator'
import { Textarea } from '@/components/ui/textarea'
import { VideoInputForm } from './forms/video-input-form'
import { RunAIForm } from './forms/run-ai-form'

export function Content() {
  const [temperature, setTemperature] = useState(0.5)

  function handlePromptSelected(template: string) {
    console.log(template)
  }

  function handleTemperatureChange(value: number) {
    setTemperature(value)
  }

  return (
    <main className="flex-1 px-6 py-4 flex gap-6">
      <div className="flex flex-col flex-1 gap-4">
        <div className="grid grid-rows-2 gap-4 flex-1">
          <Textarea
            className="resize-none p-4 leading-relaxed"
            placeholder="Enter the prompt for the AI..."
          />
          <Textarea
            className="resize-none p-4 leading-relaxed"
            placeholder="Results generated by AI..."
            readOnly
          />
        </div>

        <p className="text-sm text-muted-foreground">
          Remember: you can use the{' '}
          <code className="text-violet-400">{'{transcription}'}</code> variable
          in your prompt to insert the transcripted content of your video
        </p>
      </div>

      <div className="w-80 space-y-6">
        <VideoInputForm />

        <Separator />

        <RunAIForm
          handlePromptSelected={handlePromptSelected}
          handleTemperatureChange={handleTemperatureChange}
          temperature={temperature}
        />
      </div>
    </main>
  )
}
